sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t pawelkonczalski/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true pawelkonczalski/docker-react npm run test
