sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t pawelkonczalski/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true pawelkonczalski/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-462416932929"
  backet_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY